travis:
  secure:
    BINSTAR_TOKEN: IksrC0tIrMD2lOKW3RBmY81Xh6bjic02aIq2YzwpvXL50NxoBXxgZiCUhMuHVgguCP1Eg9pdbgrh1FaiPCgSvzb+hSFbNwrnicWbT9/Ak6/e794MOL6r0OMY1JlODeBlpIhWcyeYtfKPRWQ9AWR95e+Xj34VreDYdzPlFkQeRnbyy5/sDypQc8YJhlavW++zETgpefS9jfdVsVC3k9D+0jtifxhL2R8iugoWqVuOtOGVWgesoOpAN0vKzpZ8drJLxempOkZeXfbR7R/bzzk7L+zzxam/iJf0eaRfAgEU7ySF/o8Xv/8ZqiCN9MJaaOuxnD7okuK2cuAxfgV+B6utIYZYcWqIGi0WQwnBJhdmKY3bzYtlu9amCPNMeV+uIFHieULL1g0+eqCasIifq9lk7vmaOBpamnT9pzccCB/vxL2cEBE1q0aO0bmFNHEQwbogr2tB5iTP2rfQXiAP1Yd6fqn1gVjNqDL093pq22o+RzfJwhRmjbnWsGdPGwRdcbIcVMobAygmyUbnhHwWEVWnnjOgRcYxTnZjSJny5z3XZXMcvJc4CpeqXNaOINo2plTwIiGQpcGxL5vnzB/pGm3ecVDRcPzcDPPM2fsjvxGx3zFZfOeZHAtImT1mNKUjZFMiREB24nCAry/3M3MlH897VifpoP5lUWB/h8naHFEaf3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
